#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=6:00:00
#PBS -N rsHRF
#PBS -V

bold=$(jq -r .bold config.json)
mask=$(jq -r .mask config.json)
estimation=$(jq -r .estimation config.json)

time singularity exec -e docker://bids/rshrf rsHRF --input_file $bold results --atlas $mask --estimation $estimation

if [ ! -d results ]; then
	echo "failed to create restuls directory"
	exit 1
fi

# create product.json
cat << EOF > product.json
{
    "brainlife": [
        { 
            "type": "image/png", 
	    "name": "plot1(TBD)",
            "base64": "$(base64 -w 0 results/bold_plot_1.png)"
        },
        { 
            "type": "image/png", 
	    "name": "plot2(TBD)",
            "base64": "$(base64 -w 0 results/bold_plot_2.png)"
        }
    ]
}
EOF
echo "all done!"	


