#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=6:00:00
#PBS -N rsHRF

set -e
set -x

bold=$(jq -r .bold config.json)
mask=$(jq -r .mask config.json)
estimation=$(jq -r .estimation config.json)

time SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://bids/rshrf:1.0.0 rsHRF --input_file $bold results --atlas $mask --estimation $estimation

#1.0.1 doesn't work yet.
#time SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://bids/rshrf:1.0.1 rsHRF --n_jobs 8 --input_file $bold results --atlas $mask --estimation $estimation

    "brainlife": [
        { 
            "type": "image/png", 
	    "name": "plot1(TBD)",
            "base64": "$(base64 -w 0 results/bold_plot_1.png)"
        },
        { 
            "type": "image/png", 
	    "name": "plot2(TBD)",
            "base64": "$(base64 -w 0 results/bold_plot_2.png)"
        }
    ]
}
EOF

echo "all done!"	


